import { Gift, GiftItem } from "./interfaces";

export const itemNames: any = {
    1: "ЖК Жилет/костюм женский",
    2: "ЖБ Брюки / шорты женские",
    3: "ЖП Платье женское",
    4: "Д Домашняя одежда",
    5: "ЖО Обувь женская",
    6: "ЖС Свитер / джемпер женский",
    7: "ЖГ Головной убор / шарф / перчатки женские",
    8: "ЖВ Верхняя одежда женская",
    9: "ЖФ Блузка / рубашка женская",
    10: "ЖЮ Юбка женская",
    11: "МГ Головной убор / шарф мужской",
    12: "МВ Верхняя одежда мужская",
    13: "МС Свитер мужской",
    14: "МБ Брюки / джинсы / шорты мужские",
    15: "МО Обувь мужская",
    16: "МК Пиджак / костюм мужской",
    17: "МР Рубашка мужская",
    18: "МФ Футболка / майка мужская",
    64: "МА Галстук",
    19: "ДЖС Свитер / джемпер девочки",
    20: "ДЖП Платье девочки",
    21: "ДД Домашняя одежда детская",
    22: "ДЖО Обувь девочки",
    23: "ДЖФ Блузка / рубашка девочки",
    24: "ДЖГ Головной убор / шарф / варежки девочки",
    25: "ДЖВ Верхняя одежда девочки",
    26: "ДЖЮ Юбка девочки",
    41: "ДЖБ Брюки / шорты девочки",
    57: "ДЖБк Колготки девочки",
    59: "ДЖК Костюм/комбинезон девочки",
    60: "ДЖЖ Жилет девочки",
    61: "ДЖН Трусы, носки девочки",
    27: "ДМС Свитер мальчика",
    52: "ДМК Жилет / костюм мальчика",
    55: "ДМН Трусы / носки мальчика",
    56: "ДМБк Колготки",
    28: "ДМФ Майка мальчика",
    51: "ДМР Рубашка мальчика",
    29: "ДМБ Брюки / шорты мальчика",
    30: "ДМО Обувь мальчика",
    31: "ДМГ Головной убор / шарф мальчика",
    32: "ДМВ Верхняя одежда мальчика",
    33: "МлБд Боди",
    34: "МлФ Футболка / майка младенца",
    35: "МлБ Брючки младенца",
    36: "МлО Обувь младенца",
    37: "МлП Платье маленькой девочки",
    38: "МлЮ Юбка маленькой девочки",
    39: "МлГ Головной убор младенца",
    40: "МлВ Верхняя одежда",
    42: "МлС Свитер младенца",
    53: "МлН Носочки/царапки младенца",
    54: "МлБк Колготки/ползунки младенца",
    43: "Игрушка детская",
    44: "Сумка / рюкзак",
    45: "Посуда",
    46: "Бытовая техника",
    47: "Аксесуары",
    48: "Бытовые принадлежности",
    49: "Другое",
    50: "Ремни / пояса",
    58: "Книги",
    62: "Нижнее белье",
    63: "Канцтовары",
    65: "Журнал/брошюра"
}

export const itemRestrictions: any = {
    1: undefined,
    2: undefined,
    3: undefined,
    4: undefined,
    5: undefined,
    6: undefined,
    7: undefined,
    8: undefined,
    9: undefined,
    10: undefined,
    11: 3,
    12: 3,
    13: 3,
    14: 3,
    15: 3,
    16: 3,
    17: 3,
    18: 3,
    19: 5,
    20: 5,
    21: 5,
    22: 5,
    23: 5,
    24: 5,
    25: 5,
    26: 5,
    41: 5,
    27: 5,
    52: 5,
    28: 5,
    51: 5,
    29: 5,
    30: 5,
    31: 5,
    32: 5,
    33: 5,
    34: 5,
    35: 5,
    36: 5,
    37: 5,
    38: 5,
    39: 5,
    40: 5,
    42: 5,
    43: 5,
    53: 5,
    54: 5,
    55: 5,
    56: 5,
    57: 5,
    44: undefined,
    45: undefined,
    46: undefined,
    47: undefined,
    48: undefined,
    49: undefined,
    50: undefined,
    58: undefined,
    59: 5,
    60: 5,
    61: undefined,
    62: undefined,
    63: undefined,
    64: undefined,
    65: undefined
}

export const chlidrenItems = [
    19, 
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    41,
    27,
    52,
    28,
    51,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    42,
    43,
    53,
    54,
    55,
    56,
    57,
    59,
    60,
    61
];

export enum Generations {
    Baby = 0,
    Kid = 1,
    Teenager = 2,
    Adult = 3
}

export const itemGenerations: {[key: number]: Generations[]} = {
    1: [Generations.Adult, Generations.Teenager],
    2: [Generations.Adult, Generations.Teenager],
    3: [Generations.Adult, Generations.Teenager],
    4: [Generations.Adult, Generations.Teenager],
    5: [Generations.Adult, Generations.Teenager],
    6: [Generations.Adult, Generations.Teenager],
    7: [Generations.Adult, Generations.Teenager],
    8: [Generations.Adult, Generations.Teenager],
    9: [Generations.Adult, Generations.Teenager],
    10: [Generations.Adult, Generations.Teenager],
    11: [Generations.Adult, Generations.Teenager],
    12: [Generations.Adult, Generations.Teenager],
    13: [Generations.Adult, Generations.Teenager],
    14: [Generations.Adult, Generations.Teenager],
    15: [Generations.Adult, Generations.Teenager],
    16: [Generations.Adult, Generations.Teenager],
    17: [Generations.Adult, Generations.Teenager],
    18: [Generations.Adult, Generations.Teenager],
    19: [Generations.Kid, Generations.Teenager],
    20: [Generations.Kid, Generations.Teenager],
    21: [Generations.Kid, Generations.Teenager],
    22: [Generations.Kid, Generations.Teenager],
    23: [Generations.Kid, Generations.Teenager],
    24: [Generations.Kid, Generations.Teenager],
    25: [Generations.Kid, Generations.Teenager],
    26: [Generations.Kid, Generations.Teenager],
    41: [Generations.Kid, Generations.Teenager],
    27: [Generations.Kid, Generations.Teenager],
    52: [Generations.Kid, Generations.Teenager],
    28: [Generations.Kid, Generations.Teenager],
    51: [Generations.Kid, Generations.Teenager],
    29: [Generations.Kid, Generations.Teenager],
    30: [Generations.Kid, Generations.Teenager],
    31: [Generations.Kid, Generations.Teenager],
    32: [Generations.Kid, Generations.Teenager],
    33: [Generations.Baby],
    34: [Generations.Baby],
    35: [Generations.Baby],
    36: [Generations.Baby],
    37: [Generations.Baby],
    38: [Generations.Baby],
    39: [Generations.Baby],
    40: [Generations.Baby],
    42: [Generations.Baby],
    43: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    53: [Generations.Baby],
    54: [Generations.Baby],
    55: [Generations.Kid, Generations.Teenager],
    56: [Generations.Kid, Generations.Teenager],
    57: [Generations.Kid, Generations.Teenager],
    44: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    45: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    46: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    47: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    48: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    49: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    50: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    58: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    59: [Generations.Kid, Generations.Teenager],
    60: [Generations.Kid, Generations.Teenager],
    61: [Generations.Kid, Generations.Teenager],
    62: [Generations.Adult, Generations.Teenager],
    63: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
    64: [Generations.Adult, Generations.Teenager],
    65: [Generations.Baby, Generations.Adult, Generations.Kid, Generations.Teenager],
}

export enum Genders {
    Male = 0,
    Female =  1
}

export const itemGenders: {[key: number]: Genders[] } = {
    1: [Genders.Female],
    2: [Genders.Female],
    3: [Genders.Female],
    4: [Genders.Female],
    5: [Genders.Female],
    6: [Genders.Female],
    7: [Genders.Female],
    8: [Genders.Female],
    9: [Genders.Female],
    10: [Genders.Female],
    11: [Genders.Male],
    12: [Genders.Male],
    13: [Genders.Male],
    14: [Genders.Male],
    15: [Genders.Male],
    16: [Genders.Male],
    17: [Genders.Male],
    18: [Genders.Male],
    19: [Genders.Female],
    20: [Genders.Female],
    21: [Genders.Female],
    22: [Genders.Female],
    23: [Genders.Female],
    24: [Genders.Female],
    25: [Genders.Female],
    26: [Genders.Female],
    41: [Genders.Female],
    27: [Genders.Male],
    52: [Genders.Male],
    28: [Genders.Male],
    51: [Genders.Male],
    29: [Genders.Male],
    30: [Genders.Male],
    31: [Genders.Male],
    32: [Genders.Male],
    33: [Genders.Female, Genders.Male],
    34: [Genders.Female, Genders.Male],
    35: [Genders.Female, Genders.Male],
    36: [Genders.Female, Genders.Male],
    37: [Genders.Female, Genders.Male],
    38: [Genders.Female, Genders.Male],
    39: [Genders.Female, Genders.Male],
    40: [Genders.Female, Genders.Male],
    42: [Genders.Female, Genders.Male],
    43: [Genders.Female, Genders.Male],
    53: [Genders.Female, Genders.Male],
    54: [Genders.Female, Genders.Male],
    55: [Genders.Male],
    56: [Genders.Male],
    57: [Genders.Female],
    44: [Genders.Female, Genders.Male],
    45: [Genders.Female, Genders.Male],
    46: [Genders.Female, Genders.Male],
    47: [Genders.Female, Genders.Male],
    48: [Genders.Female, Genders.Male],
    49: [Genders.Female, Genders.Male],
    50: [Genders.Female, Genders.Male],
    58: [Genders.Female, Genders.Male],
    59: [Genders.Female],
    60: [Genders.Female],
    61: [Genders.Female],
    62: [Genders.Female],
    63: [Genders.Female, Genders.Male],
    64: [Genders.Male],
    65: [Genders.Female, Genders.Male],
}

export function isChildItem(item: GiftItem) {
    return chlidrenItems.some(x => x.toString() == item.id);
}